# Generated by Django 5.1.3 on 2024-11-26 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0003_alter_subject_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={},
        ),
    ]
